version: "3.9"

services:
  go-app:
    container_name: go-hash
    image: go-hash-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - hash_db
  hash_db:
    container_name: hash_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}